name: Build Plugin

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: ERaces
          path: build/libs/*.jar
